version: '3.1'

services:
  app:
    build: 
     context: .
     dockerfile: Dockerfile
    command: node index.js
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: BDshechka
    ports:
     - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db:5432/BDshechka -user=postgres -password=example migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
