version: "3.8"

services:

  # Служба для бази даних MySQL
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: FuckThisDatabaseLMAO69
      MYSQL_DATABASE: TransSave
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql

  # Служба для веб-додатку
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    depends_on:
      - db

  # Служба для міграції бази даних з Flyway
  flyway:
    image: boxfuse/flyway:latest
    command: -url=jdbc:mysql://db:3306/TransSave?user=${user}&password=${password} migrate
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db