version: "3.8"

services:

  # Служба для бази даних MongoDB
  db:
    # Збираємо контейнер бази даних з Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.base

    # Відкриваємо порт 27017 на зовнішньому і внутрішньому інтерфейсі
    ports:
      - "27017:27017"

    # Мапуємо локальний каталог для збереження даних MongoDB
    volumes:
      - C:\Users\varga\Enanas-Negra\volumes:/data/db

  # Служба для веб-додатку
  web:
    # Збираємо контейнер веб-додатку з Dockerfile.web
    build:
      context: .
      dockerfile: Dockerfile.web

    # Відкриваємо порт 80 на зовнішньому і внутрішньому інтерфейсі
    ports:
      - "80:80"

    # Залежимо від контейнера з базою даних
    depends_on:
      - db