# Використовуємо офіційний образ MongoDB
FROM mongo:latest

ENV MONGODB_HOST="mongodb://mongo:27017"
ENV MONGODB_DATABASE="TransHistory"
ENV MONGODB_COLLECTION="SavedHistory"


EXPOSE 27017

# Запускаємо MongoDB
CMD ["mongod"]


