version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_USER: sa
      DB_PASSWORD: "YourStrong!Passw0rd"
      DB_SERVER: db
      DB_DATABASE: YourDatabaseName
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"

  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: node-app-base